- name: payment setup
  hosts: all
  become: true
  tasks:
    - name: copy service file
      ansible.builtin.copy:
        src: payment.service
        dest: /etc/systemd/system/payment.service

    -  name:  install python
       ansible.builtin.yum:
         name:
           - python36
           - gcc
           - python3-devel
         state: installed

    -  name: add user
       ansible.builtin.user:
         name: roboshop


    - name: remove directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download unzip
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/payment.zip
        dest: /app
        args:
          chdir: /app

    - name: install python req
      ansible.builtin.shell: pip3.6 install -r requirements.txt

    - name: start payment service
      ansible.builtin.systemed:
        name: payment
        state: restart
        enabled: yes
        daemon-reload: yes
























