- name: rabbitmq setup
  hosts: all
  become: true
  tasks:
  -  name: install erlang repo
     ansible.builtin.shell: https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

  -  name: install erlang repos
     ansible.builtin.shell: https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash


  -  name: install rabbitmq server
     ansible.builtin.yum:
       name: rabbitmq server
       state: installed

  -  name: start rabbitmq service
     ansible.builtin.systemd:
       name: rabbitmq server
       state: restarted
       enable: yes


  - - name: Add Application

      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present
















#curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
#curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
#yum install rabbitmq-server -y
#systemctl enable rabbitmq-server
#systemctl start rabbitmq-server
#rabbitmqctl add_user roboshop roboshop123
#rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
